### ISSUE TITLE
Cant start Karma on windows

### ISSUE THREAD

**Issue by guizmoau** [usc-isi-i2/Web-Karma#363] opened 2017-11-09 15:14 UTC
Karma doesn't start on windows.

It says "Startingkarma..." and "Launching Karma. Go to http://localhost:8080 if it doesn't launch."
but then I can't connect on localhost:8080.

I verified my JAVA_HOME with jdk1.7.0_80 on 64 bits.
I don't know what to do more to make it works since I have no message error.
I tried by downloading Karma version v2.053 (but the file version say v1.3.3)

Any help ?

**Comment by kaushalv274** [comment] 2017-11-09 18:03
Hi,

(1) Make sure port 8080 is not in use by another application. 
(2) For Windows, you need to set heap size to be 2 GB. Please restart Karma after resetting this. (You will see option on the top right corner of Karma window)

If it still does not work, please let me know.

Thanks
Kaushal

**Comment by guizmoau** [comment] 2017-11-09 18:11
from the result of netstat -a, i confirm that the 8080 is not in use.
heap size at 2Gb and after restart of Karma still same result.

Thanks for your help and quick answer.

**Comment by kaushalv274** [comment] 2017-11-09 18:29
You should be getting a Tomcat window on startup or after restarting Karma from Karma window. 

Can you please paste logs from that window ?

Thanks

**Comment by guizmoau** [comment] 2017-11-10 08:30
I got no Tomcat window on startup neither on restarting karma from karma window.

**Comment by guizmoau** [comment] 2017-11-10 08:39
![capturekarma](https://user-images.githubusercontent.com/5398689/32649638-142fe824-c5fb-11e7-99b2-2546cc7f1297.JPG)

**Comment by akshayrana1139** [comment] 2017-11-13 06:41
I have the exact same issue. Any fix for this ??

**Comment by kaushalv274** [comment] 2017-11-13 21:22
Hi @akshayrana1139 & @guizmoau. 

Which version of windows you guys are running?

Kaushal

**Comment by akshayrana1139** [comment] 2017-11-14 05:19
Windows 10 and tried with all versions of Java. It does not start the tomcat server automatically and directly jumps to the line "Launching Karma. Go to localhost..."

Is there a way to manually start the server and then link this to that until the issue is resolved ?

**Comment by devJpv** [comment] 2017-11-14 15:34
Hi,
I am running Windows 10 64bit. 
The localhost:8080 eventually launched after reinstalling the 64 bit version of the Java JRE and running karma.exe as administrator.
I hope it helps. John-Paul
![image](https://user-images.githubusercontent.com/13219071/32788458-8664c6ba-c959-11e7-9046-da291700dba4.png)

**Comment by kaushalv274** [comment] 2017-11-14 19:05
Hi @devJpv,
Thanks for the comment. 

We have to install appropriate version of JAVA. (64 bit JAVA for 64 bit OS.) (https://github.com/usc-isi-i2/Web-Karma/wiki/Installation%3A-One-Click-Install). 

@akshayrana1139 , can you try above steps and check whether it is working or not. 

Thanks
Kaushal

**Comment by akshayrana1139** [comment] 2017-11-16 06:11
@kaushalv274 I tried everything and still the same thing. How can I start this if I manually start the tomcat.

**Comment by hlong35** [comment] 2017-11-16 19:11
I am also having guizmoau's problem launching Karma on Windows. I can confirm that port 8080 is open. It appears that java.exe is writing a rule to the firewall to block Karma. I will also check to make sure that I am running Java 64bit.
Thanks!

**Comment by kaushalv274** [comment] 2017-11-16 19:36
Hi @akshayrana1139, you can do source code install if you want to start from command line.  (https://github.com/usc-isi-i2/Web-Karma/wiki/Installation%3A-Source-Code)

@hlong35, Windows Firewall should allow karma.exe to run. 

Kaushal

**Comment by hlong35** [comment] 2017-11-17 13:53
In case this information is helpful, I am running Win 7.

Thanks--

**Comment by hlong35** [comment] 2017-11-17 14:38
SOLUTION: In case this is helpful to someone else, I got it to run:
1. Open a cmd prompt 
2. Change the directory to the tomcat\bin directory ("cd C:\Program Files\Karma-Windows\Karma-Windows\resources\app\tomcat\bin")
3. Start tomcat ("startup")
4. Then right click on Karma and run it as an administrator.

**Comment by kaushalv274** [comment] 2017-12-09 00:31
Hi everyone, 

As suggested by @hlong35, space in the path is crating issue. Make sure the installation directory does not have any space in the filepath.

Please refer to updated wiki (https://github.com/usc-isi-i2/Web-Karma/wiki/Installation%3A-One-Click-Install)

Kaushal

**Closed** 2018-01-26 23:03 UTC
Labels: installation bug

**Comment by raghav17083** [comment] 2020-05-26 14:48
I have my CATALINA_HOME set on Tomcat in some other directory. When I run startup.bat in any of the Tomcats (the one with CATALINA_HOME or the one with karma-windows/resources/app) and then run karma.exe, it opens a tomcat window but nothing else happens.
