### ISSUE TITLE
Exception when clicking on "set semantic type"

### ISSUE THREAD

**Issue by chen-regen** [usc-isi-i2/Web-Karma#269] opened 2016-07-21 15:02 UTC
I am getting following exceptions when clicking on "set semantic type" on one column from my imported excel sheet file:
```
org.apache.commons.math3.exception.TooManyIterationsException: illegal state: maximal count (100,000) exceeded: iterations
        at org.apache.commons.math3.stat.inference.KolmogorovSmirnovTest.ksSum(KolmogorovSmirnovTest.java:853)
        at org.apache.commons.math3.stat.inference.KolmogorovSmirnovTest.approximateP(KolmogorovSmirnovTest.java:931)
        at org.apache.commons.math3.stat.inference.KolmogorovSmirnovTest.kolmogorovSmirnovTest(KolmogorovSmirnovTest.java:245)
        at org.apache.commons.math3.stat.inference.KolmogorovSmirnovTest.kolmogorovSmirnovTest(KolmogorovSmirnovTest.java:271)
        at edu.isi.karma.semantictypes.numeric.KSTest.predictLabelsForColumn(KSTest.java:34)
        at edu.isi.karma.semantictypes.typinghandler.HybridSTModelHandler.predictType(HybridSTModelHandler.java:331)
        at edu.isi.karma.modeling.semantictypes.SemanticTypeUtil.predictColumnSemanticType(SemanticTypeUtil.java:226)
        at edu.isi.karma.controller.command.alignment.GetSemanticSuggestionsCommand$1.generateJson(GetSemanticSuggestionsCommand.java:80)
        at edu.isi.karma.controller.update.UpdateContainer.generateJson(UpdateContainer.java:87)
        at edu.isi.karma.controller.update.UpdateContainer.generateJson(UpdateContainer.java:120)
        at edu.isi.karma.webserver.RequestController.doPost(RequestController.java:104)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:755)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:698)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:505)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:138)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:564)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:213)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1096)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:432)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:175)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1030)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:136)
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:201)
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:109)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
        at org.eclipse.jetty.server.Server.handle(Server.java:445)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:268)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:229)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.run(AbstractConnection.java:358)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:601)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:532)
        at java.lang.Thread.run(Thread.java:745)
```

The column is simply a fake patient_id column like:
patient_id
10001
10002
10003
10004
10005

Can you advise?

**Comment by dkapoor** [comment] 2016-07-21 18:03
@minhptx: Can you have a look at this issue. Thanks.

**Comment by caknoblock** [comment] 2016-07-21 18:52
chen-regen,
When you do the set semantic type command, how many rows of data do you have loaded into Karma?

**Comment by chen-regen** [comment] 2016-07-21 18:57
Hi, 
Thanks for the response. The excel sheet only has 10 rows of data.

**Comment by chen-regen** [comment] 2016-07-21 20:02
I tried to attach the xlsx data file here but it failed. github keeps saying "we don't support that file type". If there's any other way that I can share the file with you to locate the problem, please let me know.

**Comment by dkapoor** [comment] 2016-07-21 20:15
[Workbook1.xlsx](https://github.com/usc-isi-i2/Web-Karma/files/376879/Workbook1.xlsx)

**Comment by minhptx** [comment] 2016-07-21 23:16
@dkapoor there is an error with the apache-math library we're using now. I will do the changes and make a pull request.

**Comment by dkapoor** [comment] 2016-07-22 17:07
@chen-regen, can you email your file to minhpham@usc.edu. Thanks.

**Comment by chen-regen** [comment] 2016-07-22 17:12
I have emailed the file to minhpham@usc.edu.

**Comment by dkapoor** [comment] 2016-07-25 20:06
@chen-regen: We have a fix for this and you can checkout the development branch and give it a try.
Assuming you are in you root `Web-Karma` folder, you can execute the following commands:
```
git checkout development
git pull
mvn clean install
cd karma-web
mvn jetty:run
```

**Comment by chen-regen** [comment] 2016-08-02 12:25
Hi,
I have tried this with development branch. However I am getting different error from this branch. When I do "Apply R2RML model" with my saved ttl file, I am getting following exceptions:
```
/WSP1WS8-RI-demo-data_Sheet1-auto-model.ttl
INFO [2016-08-02 08:21:01,040] (R2RMLAlignmentFileSaver->saveAlignment->110): Time to write to file:359msec
java.lang.NullPointerException
        at edu.isi.karma.view.VWorksheet.addHeaderViewPath(VWorksheet.java:383)
        at edu.isi.karma.view.VWorksheet.updateHeaderViewNodes(VWorksheet.java:364)
        at edu.isi.karma.view.ViewFactory.updateWorksheet(ViewFactory.java:93)
        at edu.isi.karma.controller.update.RegenerateWorksheetUpdate.applyUpdate(RegenerateWorksheetUpdate.java:61)
        at edu.isi.karma.controller.update.UpdateContainer.applyUpdates(UpdateContainer.java:100)
        at edu.isi.karma.webserver.RequestController.doPost(RequestController.java:103)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:755)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:698)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:505)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:138)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:564)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:213)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1096)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:432)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:175)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1030)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:136)
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:201)
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:109)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
        at org.eclipse.jetty.server.Server.handle(Server.java:445)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:268)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:229)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.run(AbstractConnection.java:358)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:601)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:532)
        at java.lang.Thread.run(Thread.java:745)
```
So I cannot confirm the fix. Can you advise? Thank you.

**Comment by dkapoor** [comment] 2016-08-02 18:07
Can you email me your karma home folder, the model and the input file so we can reproduce this new issue that you are having. My email is dipsy@isi.edu. Thanks.

**Comment by chen-regen** [comment] 2016-08-04 13:08
Hi, I have emailed a zip file including the model ttl file and input spreadsheet to dipsy@isi.edu. Thanks.

**Comment by chen-regen** [comment] 2016-08-16 14:14
Hi @dkapoor , I haven't heard anything back for this issue. I sent the files to you a while ago. Can you advise?

**Comment by caknoblock** [comment] 2016-08-16 16:34
@chen-regen, we provide support on Karma as time permits.  Right now we are in the midst of several evaluations on our funded projects and will get to the reported issues and feature requests as soon as we can.

**Comment by dkapoor** [comment] 2016-08-24 17:41
Thanks Chen. I apologize that we couldnt look at this issue earlier.
I have the model and the input file, but I would also need a zip of your karma home folder. This is the folder that you see on the bottom left corner of the Karma UI. If you havnt changed it, it would be a folder named "karma" in you user home directory.

**Comment by chen-regen** [comment] 2016-08-25 19:53
Hi @dkapoor , I have sent my karma home directory in a zip file to you. Thank you!

**Comment by dkapoor** [comment] 2016-09-07 19:45
[data-and-new-model.zip](https://github.com/usc-isi-i2/Web-Karma/files/460169/data-and-new-model.zip)
@chen-regen: The model maybe got corrupt because of the errors that you were getting. I followed the steps in your model and have re-created the model for you. It is attached to this comment. You can give it a try. 
We now have the feature to split a column on every character, you you could use that instead of the custom splitting that you were doing. I used that in this model. (You click on Split Values and then enter 'character' as the delimiter).
Also, we have a new feature that lets you see the rdfs:label of the classes and properties which could be helpful for your ontology. You can enable it from the "Settings" at the top of the Karma Navigation Bar. (You would need to pull in the latest development version)
Also, you could put your ontology files in the preloaded-ontologies subfolder of your karma home folder. That way you would not need to re-import them every time.

Thanks.

**Closed** 2016-09-07 19:45 UTC
